version: '3.7'

services:
  postgres:
    image: postgres:12
    container_name: iot_farm_postgres
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      TZ: ${DJANGO_TIME_ZONE}
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  postgres_secondary:
    image: postgres:12
    container_name: iot_farm_postgres_secondary
    env_file:
      - .env
    ports:
      - ${DATABASE_SECONDARY_PORT}:5432
    environment:
      TZ: ${DJANGO_TIME_ZONE}
    volumes:
      - postgres_secondary_volume:/var/lib/postgresql/data/

  mongo:
    image: mongo:4-bionic
    container_name: iot_farm_mongo
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_volume:/data/db

  iot_farm_api:
    build: .
    container_name: iot_farm_api
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${DJANGO_PUBLIC_PORT}:8000
    volumes:
      - ./iot_farm:/iot_farm
    depends_on:
      - postgres
      - postgres_secondary
      - mongo

  document:
    image: swaggerapi/swagger-ui
    container_name: iot_farm_api_document
    volumes:
      - ./docs:/app/docs
    ports:
      - ${SWAGGER_OPENAPI_PORT}:8080
    environment:
      SWAGGER_JSON: /app/docs/IotFramAPIs.yaml

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  postgres_volume:
  postgres_secondary_volume:
  mongo_volume:
