# Generated by Django 3.0.4 on 2020-03-05 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('device', models.CharField(help_text='Required', max_length=50, verbose_name='device')),
                ('parameter', models.CharField(help_text='Required', max_length=20, verbose_name='parameter')),
                ('value', models.FloatField(help_text='Required', verbose_name='value')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', help_text='The status of device, `ON` or `OFF`. Default: `ON`', max_length=3, verbose_name='status')),
                ('mode', models.CharField(choices=[('AUTO', 'AUTO'), ('MANUAL', 'MANUAL')], default='AUTO', help_text='The mode of device, `AUTO` or `MANUAL`. Default: `AUTO`', max_length=6, verbose_name='mode')),
                ('user', models.ForeignKey(help_text='Required.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensors',
            },
        ),
    ]
